### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Marcel00762** [ACPlayGames/DiscordNukeBot#1]
Commands dont working pls help

**Comment by ACPlayGames** [comment]
Can you further elaborate? What doesn't work? What's the error code?

**Comment by Iusedmy1stnamelol** [comment]
what do i put in .replit

**Comment by ACPlayGames** [comment]
Go to https://repl.it/~, create a Python file, and copy and paste the code there. Make sure to alter the bot token and user ID.
