### ISSUE TITLE
What do i put in .replit

### ISSUE THREAD

**Issue by Iusedmy1stnamelol** [ACPlayGames/DiscordNukeBot#2]
All it says it clear and it doesn't run

**Comment by ACPlayGames** [comment]
Are you running it on a Python file? Did you run the file? Did you alter the bot token and user ID?

**Comment by Iusedmy1stnamelol** [comment]
I fixed the problem. Thank you for making the bot.

**Comment by ACPlayGames** [comment]
No problem. Have a nice day!
